name: CI/CD for backend

on:
  push:
    paths:
      - "Backend/**"
    branches: [ "feature/backend/cd" ]
  pull_request:
    paths:
      - "Backend/**"
    branches: [ "feature/backend/cd" ]

jobs:
  CI-CD:
    runs-on: self-hosted
    env:
      working-directory: ./Backend
    steps:
    # Step 1: Check out the code from GitHub
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Build Docker image for FastAPI backend
    - name: activate venv and install dependencies
      run: |
        source env/envs/back_test/bin/activate
        pip install -r requirements.txt
      working-directory: "${{ env.working-directory }}"

    # Step 3: Run test
    - name: Run Tests
      run: |
        source env/envs/back_test/bin/activate
        pytest
      working-directory: "${{ env.working-directory }}"