name: CI/CD for backend

on:
  push:
    paths:
      - "**"
    branches: [ "feature/backend/cd" ]
  pull_request:
    paths:
      - "**"
    branches: [ "feature/backend/cd" ]

jobs:
  CI-CD:
    runs-on: self-hosted
    env:
      working-directory: ./Backend
    steps:
    # Step 1: Check out the code from GitHub
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Build Docker image for FastAPI backend
    - name: activate venv and install dependencies
      run: |
        echo "Current working directory:"
        pwd
        
        echo "Listing contents of the working directory:"
        ls -la "/home/user/env/envs/"
        echo "Checking if the environment directory exists:"
        if [ -d "./env/envs/back_test" ]; then
          echo "Directory exists!"
        else
          echo "Directory does NOT exist!"
        
        source /home/user/env/envs/back_test/bin/activate
        pip install -r requirements.txt
        
        fi
      working-directory: "${{ env.working-directory }}"

    # Step 3: Run test
    - name: Run Tests
      run: |
        source /home/user/env/envs/back_test/bin/activate
        pytest
      working-directory: "${{ env.working-directory }}"